#!/bin/sh

# Start container if not running
docker compose up --no-recreate --detach

# Stash working directory
stash=[ $(git status --porcelain=1 | wc -l) -ne 0 ]

if $stash; then
    git stash -q --keep-index
fi

# Test, lint, analyze
verify() {
    docker compose exec -T app composer test || return $?
    docker compose exec -T app composer lint || return $?
    docker compose exec -T app composer analyze || return $?
}

verify; result=$?

# Re-apply stash
if $stash; then
    git stash pop -q
fi

exit $result
