#!/bin/sh

# Start container if not running
./app up --no-recreate --detach

# Stash working directory
git stash -q --keep-index

# Test, lint, analyze
verify() {
    ./app composer test || return $?
    ./app composer lint || return $?
    ./app composer analyze || return $?
}

verify; result=$?

# Re-apply stash
git stash pop -q

exit $result
